version: "3.8"

services:
  backend:
    build: .
    container_name: backend_container
    restart: always
    environment:
      DATABASE_URL: mysql+pymysql://sql12724333:b73ANejVQI@sql12.freesqldatabase.com:3306/sql12724333
    ports:
      - "5000:5000"

  frontend:
    build: .
    container_name: frontend_container
    restart: always
    ports:
      - "3000:3000"
