version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Kharanshu23
      - MYSQL_DB=gov_user_data
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Kharanshu23
      MYSQL_DATABASE: gov_user_data
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
