# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Install Node.js dependencies
RUN npm install

# Expose the port on which the application will run
EXPOSE 3000

# Command to run the app
CMD ["npm", "start"]
